# Generated by Django 5.1.8 on 2025-04-03 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('password_reset_token', models.CharField(max_length=255)),
                ('token_expires_at', models.DateTimeField(null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['is_validated'], name='users_is_vali_0d788b_idx'), models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'), models.Index(fields=['is_enabled'], name='users_is_enab_c3c6b9_idx'), models.Index(fields=['created_at'], name='users_created_6541e9_idx'), models.Index(fields=['last_updated_at'], name='users_last_up_c6daeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'otps',
                'indexes': [models.Index(fields=['key'], name='otps_key_496193_idx'), models.Index(fields=['created_at'], name='otps_created_b35e98_idx')],
            },
        ),
    ]
