name: Linter & Type Checker
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.9.6

      - name: Format with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.9.6
          args: "format --check --diff"

  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Synchronize dependencies
        run: uv sync

      - name: Check with Pyright
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
          project: pyproject.toml
